-- PROFILES: One editable profile per authenticated user.
create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  phone text not null default '',
  gender text not null default '',
  avatar text not null default '/assets/3d67d.png'
);

-- DEMO ACCOUNTS:
-- Account IDs remain compatible with existing frontend IDs such as "main".
-- Each user has their own independent set of accounts.
create table public.demo_accounts (
  user_id uuid not null references auth.users(id) on delete cascade,
  id text not null,
  label text not null check (char_length(label) between 1 and 80),
  description text not null default ''
    check (char_length(description) <= 500),
  number text not null default '',
  primary key (user_id, id)
);

-- DEMO TRANSACTIONS:
-- Money stays in whole kobo; dates are generated by the database.
-- No card number, expiry or CVC is stored.
create table public.demo_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id text not null,
  kind text not null check (kind in ('deposit', 'withdrawal')),
  amount_kobo bigint not null
    check (amount_kobo > 0 and amount_kobo <= 9007199254740991),
  counterparty text not null,
  created_at timestamptz not null default now(),
  status text not null default 'completed'
    check (status in ('pending', 'completed', 'failed')),
  payment_method text,
  recipient_account_number text,
  recipient_bank text,
  foreign key (user_id, account_id)
    references public.demo_accounts(user_id, id)
);

-- HISTORY LOOKUP: Supports fetching each user's account activity.
create index demo_transactions_user_account_date_idx
  on public.demo_transactions (user_id, account_id, created_at desc);

-- ACCESS CONTROL:
-- Require login and isolate records by the authenticated user's ID.
alter table public.profiles enable row level security;
alter table public.demo_accounts enable row level security;
alter table public.demo_transactions enable row level security;

create policy profiles_read
  on public.profiles for select to authenticated
  using (user_id = (select auth.uid()));

create policy profiles_create
  on public.profiles for insert to authenticated
  with check (user_id = (select auth.uid()));

create policy profiles_update
  on public.profiles for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy accounts_read
  on public.demo_accounts for select to authenticated
  using (user_id = (select auth.uid()));

create policy accounts_create
  on public.demo_accounts for insert to authenticated
  with check (user_id = (select auth.uid()));

create policy transactions_read
  on public.demo_transactions for select to authenticated
  using (user_id = (select auth.uid()));

-- EXPLICIT PERMISSIONS:
-- Table auto-exposure was disabled during project creation.
-- Transactions will be written through a validated database function next.
revoke all on public.profiles,
  public.demo_accounts,
  public.demo_transactions
  from anon, authenticated;

grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.demo_accounts to authenticated;
grant select on public.demo_transactions to authenticated;